name: Build TypeTreeDumper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 完整检出以支持构建

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Generate Dia2Lib
      shell: powershell
      run: |
        .\GenDia2Lib.bat

    - name: Build solution
      run: |
        msbuild TypeTreeDumper.sln -p:Configuration=Release -p:Platform=x64 -maxcpucount
      env:
        # 如需额外环境变量，在此添加

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TypeTreeDumper-Release
        path: |
          **/*.exe
          **/*.dll  # 包含相关 DLL
        retention-days: 30
